name: Build and Upload on release

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build 
      run: dotnet publish -r win-x64 -p:PublishSingleFile=true --no-self-contained

    - name: Copy Build To Export Dir
      run: cp bin/Release/net8.0/win-x64/publish/TrainingModeDataParser.exe export/

    - name: Zip contents
      working-directory: ${{ github.workspace }}/export
      run: zip TrainingModeDataParser-win64.zip ./*

    - name: Calculate checksums
      working-directory: ${{ github.workspace }}/export
      run: | 
        md5sum TrainingModeDataParser-win64.zip | awk '{ print $1 }'> TrainingModeDataParser-win64.zip.md5
        sha256sum TrainingModeDataParser-win64.zip | awk '{ print $1 }'> TrainingModeDataParser-win64.zip.sha256

    - name: Release TrainingModeDataParser
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
            ./export/TrainingModeDataParser-win64.zip
            ./export/TrainingModeDataParser-win64.zip.md5
            ./export/TrainingModeDataParser-win64.zip.sha256
